export const mockItems = [
    {
        id: 1,
        cover: '/assets/images/mbmcportada.jpg',
        title: 'Maracucho Bueno Muere Chiquito',
        artist: 'cruz cafune',
        genre: 'Trap',
        duration: '3:45',
        year: 2018,
        type: 'Album',
        popularity: 29,
        plays: 300,
        ratings: 8.5,
        date: '2025-02-05',
        listen: 'https://www.youtube.com/watch?v=siUqDP9BapM&ab_channel=CruzCafun%C3%A9'
      },
      {
        id: 2,
        cover: '/assets/images/playavirginia.jpeg',
        title: 'Playa Virginia',
        artist: 'Delaossa',
        genre: 'Hip-Hop',
        duration: '4:10',
        year: 2022,
        type: 'Single',
        popularity: 10,
        plays: 100,
        ratings: 9.5,
        date: '2025-02-05',
        listen: 'https://www.youtube.com/watch?v=BcMDxGdxX0o&list=OLAK5uy_k5muoEdNG1Hu-0f4Wbt3nE3XNDRqKCCBs&index=6&ab_channel=DELAOSSA'
      },
      {
        id: 3,
        cover: '/assets/images/istmo.jpeg',
        title: 'Istmo',
        artist: 'Dano',
        genre: 'Rap',
        duration: '2:57',
        year: 2019,
        type: 'Album',
        popularity: 10,
        plays: 400,
        ratings: 10,
        date: '2025-02-05',
        listen: 'https://www.youtube.com/watch?v=4lWftvfc05E&ab_channel=elxcaspi'
      },
      {
        id: 4,
        cover: '/assets/images/bbo.jpeg',
        title: 'BBO',
        artist: 'Hoke',
        genre: 'Rap',
        duration: '20:56',
        year: 2022,
        type: 'Album',
        popularity: 10,
        plays: 1000,
        ratings: 9.5,
        date: '2025-02-04',
        listen: 'https://www.youtube.com/watch?v=wzFgNRaP4qo&ab_channel=HOKE'
      },
      {
        id: 5,
        cover: '/assets/images/l2po.jpg',
        title: 'Last 2 people on earth',
        artist: 'Ebano',
        genre: 'Rap',
        duration: '40:30',
        year: 2021,
        type: 'Album',
        popularity: 25,
        plays: 100,
        ratings: 10,
        date: '2025-01-30',
        listen: 'https://www.youtube.com/watch?v=krD5oHk9bNs&ab_channel=%C3%89BANO'
      },
      {
        id: 6,
        cover: '/assets/images/ehhpdsr.jpg',
        title: 'El Hombre Hace Planes Dios Se Rie',
        artist: 'Dano',
        genre: 'Rap',
        duration: '1:20:57',
        year: 2021,
        type: 'Album',
        popularity: 11,
        plays: 100,
        ratings: 9.9,
        date: '2025-02-04',
        listen: 'https://www.youtube.com/watch?v=s7aTWLNHCzw&ab_channel=DanoZiontifik'
      },      
      {
        id: 7,
        cover: '/assets/images/debi.png',
        title: 'Debí tirar mas fotos',
        artist: 'Bad Bunny',
        genre: 'Musica Tradicional Puertoriqueña',
        duration: '1:30:00',
        year: 2025,
        type: 'Album',
        popularity: 12,
        plays: 950,
        ratings: 8.5,
        date: '2025-02-04',
        listen: 'https://www.youtube.com/watch?v=y_CLlbP0DPI&ab_channel=LeoelMencho'
      },
      {
        id: 8,
        cover: '/assets/images/daltonico.jpg',
        title: 'Daltonico pero me siento azul',
        artist: 'Choclock',
        genre: 'Hip-Hop',
        duration: '40:00',
        year: 2025,
        type: 'Album',
        popularity: 40,
        plays: 800,
        ratings: 8.5,
        date: '2025-02-04',
        listen: 'https://www.youtube.com/watch?v=3iSwxUgtg6g&ab_channel=Choclock'
      },
      {
        id: 9,
        cover: '/assets/images/hammu.jpeg',
        title: 'Hammu Nation',
        artist: 'Hammurabi Kids',
        genre: 'Hip-Hop',
        duration: '20:00',
        year: 2019,
        type: 'EP',
        popularity: 5,
        plays: 100,
        ratings: 3.5,
        date: '2024-12-30',
        listen: 'https://www.youtube.com/watch?v=eD8X9nBltLs&ab_channel=GRIMEYMUSIC'
      },
      {
        id: 10,
        cover: '/assets/images/cosas.jpeg',
        title: 'Cosas Que Brillan',
        artist: 'Ebano',
        genre: 'Hip-Hop',
        duration: '30:00',
        year: 2024,
        type: 'EP',
        popularity: 15,
        plays: 100,
        ratings: 5.5,
        date: '2025-01-10',
        listen: 'https://www.youtube.com/watch?v=6DEhS9wsR2Q&ab_channel=%C3%89BANO'
      },
      {
        id: 11,
        title: 'MoonLight',
        cover: '/assets/images/moonlight.jpg',
        artist: 'Cruz Cafune',
        genre: 'Trap',
        duration: '30:00',
        year: 2024,
        type: 'EP',
        popularity: 30,
        plays: 100,
        ratings: 9.5,
        date: '2025-01-30',
        listen: 'https://www.youtube.com/watch?v=8YCkADIORQQ&ab_channel=DirtyMusic'
      },
      {
        id: 12,
        title: 'Un Perro Andaluz',
        artist: 'Delaossa',
        cover: '/assets/images/perroandaluç.jpeg',
        genre: 'Trap',
        duration: '30:00',
        year: 2019,
        type: 'EP',
        popularity: 50,
        plays: 100,
        ratings: 7.5,
        date: '2025-01-01',
        listen: 'https://www.youtube.com/watch?v=zaWQJQSZjyc&ab_channel=SpaceHammu'
      },
      {
        id: 13,
        title: 'The Kingtape',
        artist: 'Toteking',
        cover: '/assets/images/king.jpg',
        genre: 'Trap',
        duration: '30:00',
        year: 2024,
        type: 'Single',
        popularity: 150,
        plays: 100,
        ratings: 8.5,
        date: '2025-01-30',
        listen: 'https://www.youtube.com/watch?v=pMSLmqDavEI&list=PLh-0MzX1ExhzljAvnXL5he-qMEPhMa9yx&ab_channel=ToteKingOfficialVEVO'
      },
  ];
  
  export const recommendations = [
    {
        id: 1,
        cover: '/assets/images/mbmcportada.jpg',
        title: 'Maracucho Bueno Muere Chiquito',
        artist: 'Cruz Cafuné',
        genre: 'Trap',
        duration: '3:45',
        category: 'Populares',
      },
      {
        id: 2,
        cover: '/assets/images/playavirginia.jpeg',
        title: 'Playa Virginia',
        artist: 'Delaossa',
        genre: 'Hip-Hop',
        duration: '4:10',
        category: 'Populares',
      },
      {
        id: 3,
        cover: '/assets/images/istmo.jpeg',
        title: 'Istmo',
        artist: 'Dano',
        genre: 'Rap',
        duration: '2:57',
        category: 'Tendencias',
      },
      {
        id: 4,
        cover: '/assets/images/bbo.jpeg',
        title: 'BBO',
        artist: 'Hoke',
        genre: 'Rap',
        duration: '20:56',
        category: 'Tendencias',
      },
      {
        id: 5,
        cover: '/assets/images/debi.png',
        title: 'Debí tirar mas fotos',
        artist: 'Bad Bunny',
        genre: 'Musica Tradicional Puertoriqueña',
        duration: '1:30:00',
        category: 'Nuevos Lanzamientos',
      },
      {
        id: 6,
        cover: '/assets/images/daltonico.jpg',
        title: 'Daltonico pero me siento azul',
        artist: 'Chocklock',
        genre: 'Rhythm and blues',
        duration: '40:00',
        category: 'Nuevos Lanzamientos',
      },
    // ... Resto de los objetos de RecommendationsList
  ];
  
  export const songs = [
    {
        id: 1,
        title: 'MoonLight',
        artist: 'Cruz Cafuné',
        image: '/assets/images/moonlight.jpg'
      },
      {
        id: 2,
        title: 'Un Perro Andaluz',
        artist: 'Delaossa',
        image: '/assets/images/perroandaluç.jpeg'
      },
      {
        id: 3,
        title: 'Last 2 people on earth',
        artist: 'Ébano',
        image: '/assets/images/l2po.jpg'
      },
      {
        id: 4,
        title: 'Istmo',
        artist: 'Dano',
        image: '/assets/images/istmo.jpeg'
      },
      {
        id: 5,
        title: 'Maracucho Bueno Muere Chiquito',
        artist: 'Cruz Cafuné',
        image: '/assets/images/mbmcportada.jpg'
      },
      {
        id: 7,
        title: 'Hammu Nation',
        artist: 'Space Hammu',
        image: '/assets/images/hammu.jpeg'
      },
      {
        id: 8,
        title: 'Playa Virginia',
        artist: 'Delaossa',
        image: '/assets/images/playavirginia.jpeg'
      },
      {
        id: 9,
        title: 'Cosas Que Brillan',
        artist: 'Ébano',
        image: '/assets/images/cosas.jpeg'
      },
      {
        id: 10,
        title: 'BBO',
        artist: 'Hoke',
        image: '/assets/images/bbo.jpeg'
      },
  ];